import time


def format_report(raw_report: dict, report_type: str = "executive", tone: str = "professional") -> str:
    """
    Converts raw agent output into a polished, human-readable ClauseAI report
    """

    # Report titles based on type
    headers = {
        "executive": "📄 Executive Contract Summary",
        "legal": "⚖️ Legal Risk Analysis Report",
        "finance": "💰 Financial Risk Assessment",
        "full": "🧠 Full AI Contract Audit"
    }

    # Cover / Header
    report = f"""# {headers.get(report_type, "AI Contract Report")}

**Generated On:** {time.strftime('%d %b %Y')}  
**Report Type:** {report_type.capitalize()}  
**Tone:** {tone.capitalize()}  
**Engine:** ClauseAI – Multi-Agent LangGraph  

---

## 📌 Overview
This report is generated using **ClauseAI**, an intelligent contract audit
system that performs legal, financial, compliance, and risk analysis using
parallel AI agents.

---

"""

    # Body sections
    for section, content in raw_report.items():
        report += f"## {section.capitalize()}\n"
        report += f"{content}\n\n"

    # Tone note
    if tone == "simple":
        report += "_This report is simplified for non-technical readers._\n\n"

    elif tone == "technical":
        report += "_This report is intended for legal and technical professionals._\n\n"

    # Footer
    report += """
---
**Generated by ClauseAI – Intelligent Contract Audit System**  
⚡ Powered by Multi-Agent AI & LangGraph
"""

    return report