import io
import base64
import ast
import re

# --- 1. CLEANING HELPER (The "Sanitizer") ---
def clean_for_html(raw_data):
    """
    Cleans AI output for HTML.
    Removes JSON wrappers, signatures, and converts Markdown to HTML.
    """
    text = str(raw_data).strip()
    
    # A. Parse Dictionary/JSON Structure
    try:
        if (text.startswith("{") and text.endswith("}")) or (text.startswith("[") and text.endswith("]")):
            parsed = ast.literal_eval(text)
            if isinstance(parsed, list) and len(parsed) > 0:
                text = parsed[0].get('text', str(parsed[0])) if isinstance(parsed[0], dict) else str(parsed[0])
            elif isinstance(parsed, dict):
                text = parsed.get('text', str(parsed))
    except:
        pass 

    # B. Brute Force Cleanup
    if "{'type': 'text'" in text:
        start = text.find("'text': '")
        if start != -1: text = text[start + 9:]
    
    # Remove signatures/extras
    extras_markers = ["', 'extras':", '", "extras":', "', 'type':"]
    for marker in extras_markers:
        if marker in text: text = text.split(marker)[0]

    # C. Formatting Cleanup
    text = text.replace("\\n", "\n").replace("\\'", "'").replace('"', '"').replace("'", "'")
    text = text.rstrip("'\"}]")
    
    # D. HTML Specific Formatting
    # 1. Convert Newlines to <br>
    text = text.replace("\n", "<br>")
    
    # 2. Convert Markdown Bold (**text**) to HTML Bold (<b>text</b>)
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    
    # 3. Convert Headers (### Title) to HTML Headers
    text = re.sub(r'#{2,}\s?(.*)', r'<h3>\1</h3>', text)
    
    return text.strip()

# --- 2. HTML GENERATOR ---
def generate_html(results, config, filename):
    """
    Generates a high-fidelity HTML report that renders Tamil/Hindi perfectly.
    """
    tone = config.get("tone", "Standard")
    language = config.get("language", "English")
    
    # CSS for Professional Legal Look (Dark Mode compatible)
    css = """
    <style>
        body { font-family: 'Noto Sans', 'Arial', sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 0 auto; padding: 40px; background-color: #f4f4f9; }
        .container { background: white; padding: 50px; border-radius: 8px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }
        h1 { color: #003366; text-align: center; border-bottom: 2px solid #003366; padding-bottom: 10px; }
        h2 { color: #0055a5; margin-top: 30px; border-left: 5px solid #0055a5; padding-left: 10px; }
        h3 { color: #444; margin-top: 20px; font-weight: bold; }
        .meta { text-align: center; color: #666; font-size: 0.9em; margin-bottom: 40px; }
        .box { padding: 15px; border-radius: 5px; margin-bottom: 20px; border: 1px solid #ddd; }
        .legal { background-color: #e6f3ff; border-left: 5px solid #0066cc; }
        .finance { background-color: #e6fffa; border-left: 5px solid #00cc99; }
        .compliance { background-color: #fff0f0; border-left: 5px solid #ff3333; }
        .operations { background-color: #f0f4f8; border-left: 5px solid #607d8b; }
        .synthesis { background-color: #fff8e1; border-left: 5px solid #ffc107; font-size: 1.1em; }
        .footer { margin-top: 50px; text-align: center; font-size: 0.8em; color: #aaa; border-top: 1px solid #ddd; padding-top: 20px; }
    </style>
    """
    
    html = f"""
    <!DOCTYPE html>
    <html lang="{language}">
    <head>
        <meta charset="UTF-8">
        <title>ClauseAI Audit - {filename}</title>
        {css}
    </head>
    <body>
        <div class="container">
            <h1>CLAUSE.AI AUDIT REPORT</h1>
            <div class="meta">
                <b>Filename:</b> {filename} | <b>Tone:</b> {tone}<br>
                generated by Neural Parallel Grid
            </div>
    """

    # 1. EXECUTIVE SYNTHESIS
    if "synthesis" in results:
        raw = results["synthesis"].get("summary", "")
        clean_text = clean_for_html(raw) # <--- Clean it!
        
        html += f"""
        <div class="box synthesis">
            <h2>EXECUTIVE SYNTHESIS</h2>
            <p>{clean_text}</p>
        </div>
        """

    # 2. AGENT SECTIONS
    agents = [
        ("LEGAL RISK ANALYSIS", "legal", "legal"),
        ("FINANCIAL AUDIT", "finance", "finance"),
        ("COMPLIANCE CHECK", "compliance", "compliance"),
        ("OPERATIONAL REVIEW", "operations", "operations")
    ]

    for title, key, css_class in agents:
        if key in results:
            raw = results[key].get("summary", "")
            clean_text = clean_for_html(raw) # <--- Clean it!
            
            if clean_text:
                html += f"""
                <div class="box {css_class}">
                    <h2>{title}</h2>
                    <p>{clean_text}</p>
                </div>
                """

    html += """
            <div class="footer">
                CONFIDENTIAL - GENERATED BY CLAUSE.AI NEURAL SYSTEM
            </div>
        </div>
    </body>
    </html>
    """
    
    return html.encode('utf-8')